import { describe, it, expect } from "vitest";
import { refine } from "../src/refinement";
import type { LLMClient } from "../src/refinement";
import type { StyleSignal } from "../src/types";

function createMockLLM(response: string): LLMClient {
  return {
    chat: async () => response,
  };
}

const sampleSignals: StyleSignal[] = [
  {
    category: "communication",
    content: "偏好直接给出完整代码",
    evidence: "用户说'直接给完整的代码就行'",
    confidence: "high",
    source: "explicit",
  },
  {
    category: "toolchain",
    content: "使用 pnpm 而非 npm",
    evidence: "用户说'以后都用 pnpm'",
    confidence: "high",
    source: "explicit",
  },
];

describe("refine", () => {
  it("returns empty array when no signals provided", async () => {
    const llm = createMockLLM("[]");
    const result = await refine([], llm, "");
    expect(result).toEqual([]);
  });

  it("parses valid LLM response into StyleProposal array", async () => {
    const llm = createMockLLM(
      JSON.stringify([
        {
          action: "append",
          category: "communication",
          content: "偏好直接给出完整代码",
          reason: "用户明确要求",
        },
      ]),
    );
    const result = await refine(sampleSignals, llm, "# User Profile & Style\n\n\n");
    expect(result).toHaveLength(1);
    expect(result[0]!.action).toBe("append");
    expect(result[0]!.category).toBe("communication");
  });

  it("returns empty array when LLM returns invalid JSON", async () => {
    const llm = createMockLLM("not json at all");
    const result = await refine(sampleSignals, llm, "");
    expect(result).toEqual([]);
  });

  it("returns empty array when LLM returns invalid schema", async () => {
    const llm = createMockLLM(
      JSON.stringify([{ action: "invalid_action", category: "unknown" }]),
    );
    const result = await refine(sampleSignals, llm, "");
    expect(result).toEqual([]);
  });

  it("returns empty array when LLM returns empty array", async () => {
    const llm = createMockLLM("[]");
    const result = await refine(sampleSignals, llm, "");
    expect(result).toEqual([]);
  });

  it("filters out empty content proposals", async () => {
    const llm = createMockLLM(
      JSON.stringify([
        {
          action: "append",
          category: "communication",
          content: "",
          reason: "empty",
        },
        {
          action: "append",
          category: "toolchain",
          content: "使用 pnpm",
          reason: "valid",
        },
      ]),
    );
    const result = await refine(sampleSignals, llm, "");
    expect(result).toHaveLength(1);
    expect(result[0]!.content).toBe("使用 pnpm");
  });

  it("works with non-empty USER.md content", async () => {
    const existingMd = `# User Profile & Style

> Auto-generated by opencode-memx. Last updated: 2026-07-29

## 沟通与交互风格
- [2026-07-28] 回答技术问题时先给结论，再展开推导过程
`;

    const llm = createMockLLM(
      JSON.stringify([
        {
          action: "update",
          category: "communication",
          content: "偏好直接给出完整代码而非分步骤解释",
          target_line: 6,
          reason: "用户新偏好",
        },
      ]),
    );
    const result = await refine(sampleSignals, llm, existingMd);
    expect(result).toHaveLength(1);
    expect(result[0]!.action).toBe("update");
    expect(result[0]!.target_line).toBe(6);
  });
});
