import { describe, it, expect } from "vitest";
import {
  parseUserMd,
  serializeUserMd,
  isOverLimit,
  applyProposal,
  writeUserMd,
  readUserMd,
  backupUserMd,
} from "../src/user-md";
import { existsSync, unlinkSync } from "fs";
import type { StyleProposal } from "../src/types";

const SAMPLE = `# User Profile & Style

> Auto-generated by opencode-memx. Last updated: 2026-07-29

## 沟通与交互风格
- [2026-07-29] 偏好直接给出重构后的完整代码，而非分步骤解释
- [2026-07-28] 回答技术问题时先给结论，再展开推导过程

## 工具与环境偏好
- [2026-07-25] 使用 pnpm 而非 npm/yarn
- [2026-07-20] 编辑器为 Neovim，终端为 WezTerm

## 架构与技术决策
- [2026-07-22] 新项目默认使用 SvelteKit + Drizzle ORM

## 踩坑与禁忌
- [2026-07-27] 不要在代码注释中使用 Emoji
- ~~[2026-07-15] 偏好 Vue 3 Composition API~~ (Deprecated: 已迁移至 Svelte)
`;

describe("parseUserMd", () => {
  it("parses a complete USER.md into 4 sections", () => {
    const sections = parseUserMd(SAMPLE);
    expect(sections).toHaveLength(4);
  });

  it("parses communication section with 2 entries", () => {
    const sections = parseUserMd(SAMPLE);
    const comm = sections.find((s) => s.category === "communication");
    expect(comm).toBeDefined();
    expect(comm!.lines).toHaveLength(2);
  });

  it("parses deprecated entry correctly", () => {
    const sections = parseUserMd(SAMPLE);
    const pitfall = sections.find((s) => s.category === "pitfall");
    expect(pitfall).toBeDefined();
    const deprecated = pitfall!.lines.find((l) => l.deprecated);
    expect(deprecated).toBeDefined();
    expect(deprecated!.date).toBe("2026-07-15");
  });

  it("handles empty content gracefully", () => {
    const sections = parseUserMd("");
    expect(sections).toHaveLength(4);
    for (const s of sections) {
      expect(s.lines).toHaveLength(0);
    }
  });

  it("preserves original line numbers", () => {
    const sections = parseUserMd(SAMPLE);
    const comm = sections.find((s) => s.category === "communication")!;
    expect(comm.lines[0]!.lineNumber).toBe(6);
  });
});

describe("serializeUserMd", () => {
  it("produces valid markdown from parsed sections", () => {
    const sections = parseUserMd(SAMPLE);
    const serialized = serializeUserMd(sections, "2026-07-29");
    expect(serialized).toContain("# User Profile & Style");
    expect(serialized).toContain("## 沟通与交互风格");
    expect(serialized).toContain("## 踩坑与禁忌");
  });

  it("includes last updated line", () => {
    const sections = parseUserMd(SAMPLE);
    const serialized = serializeUserMd(sections, "2026-07-29");
    expect(serialized).toContain("2026-07-29");
  });
});

describe("isOverLimit", () => {
  it("returns false for content under limit", () => {
    expect(isOverLimit("line1\nline2\n", 10)).toBe(false);
  });

  it("returns true for content over limit", () => {
    const content = Array.from({ length: 250 }, (_, i) => `line ${i}`).join("\n");
    expect(isOverLimit(content, 200)).toBe(true);
  });
});

describe("applyProposal", () => {
  it("appends a new entry to the correct section", () => {
    const proposal: StyleProposal = {
      action: "append",
      category: "communication",
      content: "测试用偏好条目",
      reason: "测试",
    };
    const result = applyProposal(proposal, SAMPLE);
    expect(result).toContain("测试用偏好条目");
    expect(result).toContain("## 沟通与交互风格");
  });

  it("creates section if it does not exist", () => {
    const emptyDoc = `# User Profile & Style\n\n> Auto-generated by opencode-memx. Last updated: 2026-07-29\n`;
    const proposal: StyleProposal = {
      action: "append",
      category: "toolchain",
      content: "测试工具偏好",
      reason: "测试",
    };
    const result = applyProposal(proposal, emptyDoc);
    expect(result).toContain("## 工具与环境偏好");
    expect(result).toContain("测试工具偏好");
  });

  it("deprecates an existing entry by line number", () => {
    const sections = parseUserMd(SAMPLE);
    const pitfall = sections.find((s) => s.category === "pitfall")!;
    const targetLine = pitfall.lines[0]!.lineNumber;

    const proposal: StyleProposal = {
      action: "deprecate",
      category: "pitfall",
      content: "不再适用",
      target_line: targetLine,
      reason: "测试废弃",
    };
    const result = applyProposal(proposal, SAMPLE);
    expect(result).toContain("~~");
    expect(result).toContain("(Deprecated: 不再适用)");
  });

  it("updates an existing entry by line number", () => {
    const sections = parseUserMd(SAMPLE);
    const comm = sections.find((s) => s.category === "communication")!;
    const targetLine = comm.lines[0]!.lineNumber;

    const proposal: StyleProposal = {
      action: "update",
      category: "communication",
      content: "更新后的偏好",
      target_line: targetLine,
      reason: "测试更新",
    };
    const result = applyProposal(proposal, SAMPLE);
    expect(result).toContain("更新后的偏好");
  });
});

describe("readUserMd / writeUserMd", () => {
  const testContent = `# User Profile & Style\n\n> Auto-generated by opencode-memx. Last updated: 2026-07-29\n\n## 沟通与交互风格\n- [2026-07-29] 测试条目\n`;

  it("writes and reads back content", () => {
    writeUserMd(testContent);
    const read = readUserMd();
    expect(read).toContain("测试条目");
    expect(read).toContain("# User Profile & Style");
  });
});

describe("backupUserMd", () => {
  it("creates a backup file", () => {
    const bakPath = backupUserMd();
    expect(bakPath).toBeTypeOf("string");
    expect(existsSync(bakPath!)).toBe(true);
    if (bakPath) unlinkSync(bakPath);
  });
});
