import { readFileSync, writeFileSync, renameSync, mkdirSync, existsSync, readdirSync, unlinkSync } from "fs";
import { join, basename } from "path";
import { homedir } from "os";
import type { UserMdSection, StyleProposal } from "./types";
import { CATEGORY_HEADERS, HEADER_TO_CATEGORY, CATEGORIES, type Category } from "./types";

const ENTRY_REGEX = /^- (~~)?\[(\d{4}-\d{2}-\d{2})\]\s+(.+?)(~~)?(?:\s+\(Deprecated:.*\))?$/;

export function getUserMdPath(): string {
  return join(homedir(), ".opencode", "USER.md");
}

function ensureDir(): void {
  const dir = join(homedir(), ".opencode");
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

export function readUserMd(): string {
  const path = getUserMdPath();
  if (!existsSync(path)) {
    return "";
  }
  return readFileSync(path, "utf-8");
}

export function writeUserMd(content: string): void {
  ensureDir();
  const path = getUserMdPath();

  if (existsSync(path)) {
    backupUserMd();
    cleanupOldBackups(5);
  }

  const tmpPath = `${path}.tmp.${Date.now()}`;
  writeFileSync(tmpPath, content, "utf-8");
  renameSync(tmpPath, path);
}

export function parseUserMd(content: string): UserMdSection[] {
  if (!content.trim()) {
    return CATEGORIES.map((cat) => ({
      header: CATEGORY_HEADERS[cat],
      category: cat,
      lines: [],
    }));
  }

  const lines = content.split("\n");
  const sections: UserMdSection[] = [];
  let currentSection: UserMdSection | null = null;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    const headerMatch = line.match(/^## (.+)$/);
    if (headerMatch) {
      const header = headerMatch[1]!;
      const cat = HEADER_TO_CATEGORY[header];
      if (cat) {
        currentSection = { header, category: cat, lines: [] };
        sections.push(currentSection);
      }
      continue;
    }

    const entryMatch = line.match(ENTRY_REGEX);
    if (entryMatch && currentSection) {
      const date = entryMatch[2] ?? "";
      const text = entryMatch[3] ?? "";
      currentSection.lines.push({
        raw: line,
        date,
        text,
        deprecated: !!entryMatch[1],
        lineNumber: i + 1,
      });
    }
  }

  return sections;
}

export function serializeUserMd(sections: UserMdSection[], lastUpdated?: string): string {
  const date = lastUpdated ?? new Date().toISOString().split("T")[0] ?? "";
  const result: string[] = [
    "# User Profile & Style",
    "",
    `> Auto-generated by opencode-memx. Last updated: ${date}`,
    "",
  ];

  for (const section of sections) {
    if (section.lines.length === 0) continue;
    result.push(`## ${section.header}`);
    for (const entry of section.lines) {
      result.push(entry.raw);
    }
    result.push("");
  }

  return result.join("\n");
}

export function backupUserMd(): string | null {
  const path = getUserMdPath();
  if (!existsSync(path)) return null;
  const bakPath = `${path}.bak.${Date.now()}`;
  const content = readFileSync(path, "utf-8");
  writeFileSync(bakPath, content, "utf-8");
  return bakPath;
}

export function cleanupOldBackups(maxKeep = 5): void {
  const dir = join(homedir(), ".opencode");
  if (!existsSync(dir)) return;

  const prefix = `${basename(getUserMdPath())}.bak.`;
  const backups = readdirSync(dir)
    .filter((f) => f.startsWith(prefix))
    .map((f) => join(dir, f))
    .sort()
    .reverse();

  for (const old of backups.slice(maxKeep)) {
    try {
      unlinkSync(old);
    } catch {
      // ignore
    }
  }
}

export function isOverLimit(content: string, limit = 200): boolean {
  return content.split("\n").length > limit;
}

export function applyProposal(proposal: StyleProposal, content: string): string {
  const sections = parseUserMd(content);
  const today = new Date().toISOString().split("T")[0] ?? "";
  const cat = proposal.category as Category;
  const header = CATEGORY_HEADERS[cat];

  let targetSection = sections.find((s) => s.category === cat);
  if (!targetSection) {
    targetSection = { header, category: cat, lines: [] };
    sections.push(targetSection);
  }

  const newRaw = `- [${today}] ${proposal.content}`;

  switch (proposal.action) {
    case "append": {
      targetSection.lines.push({
        raw: newRaw,
        date: today,
        text: proposal.content,
        deprecated: false,
        lineNumber: 0,
      });
      break;
    }
    case "update": {
      let found = false;
      for (const section of sections) {
        const idx = section.lines.findIndex(
          (e) => proposal.target_line != null && e.lineNumber === proposal.target_line,
        );
        if (idx !== -1) {
          section.lines[idx] = {
            raw: newRaw,
            date: today,
            text: proposal.content,
            deprecated: false,
            lineNumber: 0,
          };
          found = true;
          break;
        }
      }
      if (!found) {
        targetSection.lines.push({
          raw: newRaw,
          date: today,
          text: proposal.content,
          deprecated: false,
          lineNumber: 0,
        });
      }
      break;
    }
    case "deprecate": {
      for (const section of sections) {
        const target = section.lines.find(
          (e) => proposal.target_line != null && e.lineNumber === proposal.target_line,
        );
        if (target && !target.deprecated) {
          target.raw = `- ~~[${target.date}] ${target.text}~~ (Deprecated: ${proposal.content})`;
          target.deprecated = true;
          break;
        }
      }
      break;
    }
  }

  return serializeUserMd(sections);
}
